import type { TrialResult } from './types.js'

export const SAMPLE_VERDICTS = [
  {
    id: 'sample_001',
    tribunalType: 'relationship',
    verdict: 'Guilty, with mitigating circumstances',
    charge: 'Weaponizing busyness as a substitute for emotional honesty.',
    score: 72,
    scoreLabel: 'Asshole Score',
    caseSummary: 'The defendant ghosted a close friend for three weeks while overwhelmed, offering no explanation.',
    caseText: "I ghosted a close friend for three weeks because I was overwhelmed and didn't want to explain myself.",
    sentence: 'Send one honest message. Under 120 words. No dramatic monologue.',
    isExample: true,
    shareCard: {
      caseNumber: '00421',
      headline: 'THE TRIBUNAL HAS SPOKEN',
      shortCase: 'I ghosted a friend for three weeks.',
      verdict: 'Guilty, with mitigating circumstances',
      charge: 'Cowardice disguised as self-care.',
      recognized: 'You were genuinely overwhelmed.',
      rejected: 'That silence counts as communication.',
      sentence: 'Send one honest message under 120 words.',
    },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'sample_002',
    tribunalType: 'moral',
    verdict: 'Technically innocent, spiritually guilty',
    charge: 'Violating the categorical imperative with a smile.',
    score: 61,
    scoreLabel: 'Immorality Score',
    caseSummary: 'The defendant lied to spare a friend\'s feelings about a creative project they had worked on for months.',
    caseText: "I told a friend their creative project was great when I honestly thought it was mediocre, because I didn't want to hurt them.",
    sentence: 'Find one true thing to say. Praise it. Build from there.',
    isExample: true,
    shareCard: {
      caseNumber: '01837',
      headline: 'THE TRIBUNAL HAS SPOKEN',
      shortCase: 'I lied to avoid hurting someone\'s feelings.',
      verdict: 'Technically innocent, spiritually guilty',
      charge: 'Violating the categorical imperative with a smile.',
      recognized: 'Your motive was kindness.',
      rejected: 'That kindness was conditional on your comfort.',
      sentence: 'Find one true thing to say. Praise it. Build from there.',
    },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'sample_003',
    tribunalType: 'idea',
    verdict: 'Guilty of founder delusion',
    charge: 'Mistaking enthusiasm for a market.',
    score: 78,
    scoreLabel: 'Concept Sillyness Score',
    caseSummary: 'The defendant purchased a domain name for a startup before defining the product, target user, or revenue model.',
    caseText: "I bought a domain for a startup idea before I knew what the product was, who the customer was, or whether anyone would want it.",
    sentence: 'Talk to five potential users before buying another domain.',
    isExample: true,
    shareCard: {
      caseNumber: '02954',
      headline: 'THE TRIBUNAL HAS SPOKEN',
      shortCase: 'I bought a domain before knowing what the product was.',
      verdict: 'Guilty of founder delusion',
      charge: 'Mistaking enthusiasm for a market.',
      recognized: 'The energy is real.',
      rejected: 'That a domain name is a business plan.',
      sentence: 'Talk to five potential users before buying another domain.',
    },
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'sample_004',
    tribunalType: 'opinion',
    verdict: 'Mostly correct, badly framed',
    charge: 'Smuggling a valid critique inside a provocative overstatement.',
    score: 44,
    scoreLabel: 'Argument Weakness Score',
    caseSummary: 'The defendant argued that most productivity advice is secular religion for anxious people.',
    caseText: "Most productivity advice is secular religion for anxious people. It doesn't make you more effective. It just lets you feel virtuous about being busy.",
    sentence: 'Make the actual argument. It\'s stronger without the performance.',
    isExample: true,
    shareCard: {
      caseNumber: '03612',
      headline: 'THE TRIBUNAL HAS SPOKEN',
      shortCase: 'Most productivity advice is secular religion for anxious people.',
      verdict: 'Mostly correct, badly framed',
      charge: 'Smuggling a valid critique inside a provocative overstatement.',
      recognized: 'The underlying critique has genuine merit.',
      rejected: 'That cynicism substitutes for a better alternative.',
      sentence: 'Make the actual argument. It\'s stronger without the performance.',
    },
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
]

export function getSampleTrial(id: string): TrialResult | null {
  const sample = SAMPLE_VERDICTS.find((s) => s.id === id)
  if (!sample) return null
  return {
    id: sample.id,
    caseText: sample.caseText,
    caseSummary: sample.caseSummary,
    tribunalType: sample.tribunalType,
    createdAt: sample.createdAt,
    completedAt: sample.createdAt,
    status: 'completed',
    charge: sample.charge,
    verdict: sample.verdict,
    score: sample.score,
    scoreLabel: sample.scoreLabel,
    prosecution: { title: 'The case against you', argument: '' },
    defense: { title: 'The best defense', argument: '' },
    panelJudgments: [],
    finalReasoning: '',
    sentence: sample.sentence,
    shareCard: sample.shareCard,
    appealOfId: null,
    appealGround: null,
    appealText: null,
    isPublic: true,
  }
}
